travis:
  secure:
    BINSTAR_TOKEN: EBpcilEl+VEC2VH9LwVmDV4KiKfGntB+ObV+JyNN5eU+mGPe0Pex5ql9G7t5kSIkxCiX8VX/ffWreOGlJKSe/ZeKKRwUfVl74Ax/bT0FbI/bsgq7xaZ4OUs/ayJcwSznQXhA3QWok3H/UJNyw1KsImSWG9fFd/V9ot6ffVEKoqdz/1ZsoCZ111wYzKNVccQdHB7NxTBQ9wLoI0x6CVb0uQ9YKPKhFiWQWaOs41iOHQrmzBVAmvSXOUbTrsAId1S/35inMq915d2rWMOmfvo34dT3wGfCsjeQVr6EwyjxB3+13UDlCWo1SSjUoyXGyOI7G67Eh7L04wElsaE2aj2cLzkbBssWsZyPGXvToZ7SNzWvKZDdAJ9nDVGdh5kE9Cekoy0sGB9vd7Ilxrg+dzPoUdNt/OrTIT6f5hFqcqI3GkwQwEzsAMlAPNcHs9RFOYijITq52XJP66AXcGbiTVJOJAHIRRePE0EI61d5RmeIHPzDOdKrA8jqubk+j446uVsME1ElVuhg/81Kl+aTXRaAVEH/2FgcO1EkwnbMvuwyIdEyBCta75MABOr0OqRlxdSEmnl8vx37mtZJsOJSlysvQ4DCyveFSTfPn0wOZmHr8mtHLn25wmBEmjt/neqdynNAq3jM55L7X19iIs1fEHpjLKqsHtLVXZDB6woo5GcDkWo=
conda_forge_output_validation: true
bot:
  automerge: true
